name: Docker build dev deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Push to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Docker authentication
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker image build
        run: |
          cd $GITHUB_WORKSPACE
          docker build -t anilgadwal/nestjs-auth .
        
      - name: Push docker image to dockerhub
        run: |
          cd $GITHUB_WORKSPACE
          docker push anilgadwal/nestjs-auth
